/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "T01_counter.h"


void
counter_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *limpa_1_arg;
	void  *result_2;
	int  inc_1_arg;
	int  *result_3;
	char *consulta_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, COUNTER, COUNTER_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = limpa_1((void*)&limpa_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = inc_1(&inc_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = consulta_1((void*)&consulta_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	counter_1 (host);
exit (0);
}
