/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COUNTER_H_RPCGEN
#define _COUNTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define COUNTER 45484
#define COUNTER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define limpa 0
extern  void * limpa_1(void *, CLIENT *);
extern  void * limpa_1_svc(void *, struct svc_req *);
#define inc 1
extern  void * inc_1(int *, CLIENT *);
extern  void * inc_1_svc(int *, struct svc_req *);
#define consulta 2
extern  int * consulta_1(void *, CLIENT *);
extern  int * consulta_1_svc(void *, struct svc_req *);
extern int counter_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define limpa 0
extern  void * limpa_1();
extern  void * limpa_1_svc();
#define inc 1
extern  void * inc_1();
extern  void * inc_1_svc();
#define consulta 2
extern  int * consulta_1();
extern  int * consulta_1_svc();
extern int counter_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COUNTER_H_RPCGEN */
